# Generated by Django 2.0 on 2017-12-23 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171220_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetitor',
            name='cooperate',
            field=models.ManyToManyField(related_name='cooperated', to=settings.AUTH_USER_MODEL),
        ),
    ]
